@WebApiAuthentication_HostAddress = https://localhost:7297
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiRURZIiwiZW1haWwiOiJqYWNrLnNpbHZhQGhhcHZpZGEuY29tLmJyIiwibmFtZWlkIjoiMCIsImlhdCI6MTc0ODk1NDU5OCwianRpIjoiMTM3YjdlYjQtMzczYS00NTQwLWE1MTMtZTQwNzY1NzQ4MWQxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiUHJlbWl1bSIsIm5iZiI6MTc0ODk1NDYwMywiZXhwIjoxNzQ5MDQwOTk4LCJpc3MiOiJBdXRoQ29udHJvbGxlciIsImF1ZCI6Ind3dy5teWFwcC5jb20ifQ.k5wVtuDH91_2TTa7FhlzQ1dd9GCL7iAkLKVqTzSv5wg

GET {{WebApiAuthentication_HostAddress}}/api/v1/user/profile
Authorization: Bearer {{access_token}}
Accept: application/json
###
