# For more info on HTTP files go to https://aka.ms/vs/httpfile


@BASEPATH=https://localhost
@port=7297
@token=5dQmguc/1wU80BhdEP8wNSuceJgU2Vk8hU2wsSToNgMYpJ4vY3H3GApXhUuZH2b3zBtNAdX0KV1K5jnGZd4WMA==


GET {{BASEPATH}}:{{port}}/userbytoken/{{token}}
Content-Type: application/json
Header: Accept-Language: en-US